import Image from "next/image";
import { notFound } from "next/navigation";
import { CheckCircle2 } from "lucide-react";
import { InquiryForm } from "@/components/InquiryForm";
import { products } from "@/data/products";
import { pageMetadata } from "@/lib/seo";
export function generateStaticParams(){return products.map((p)=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const p=products.find((x)=>x.slug===slug); return pageMetadata(p?.name??"Product", p?.description, `/products/${slug}`);}
export default async function ProductDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const p=products.find((x)=>x.slug===slug); if(!p) notFound(); return <main className="container-pad py-20"><div className="grid gap-10 lg:grid-cols-2"><Image src={p.image} alt={p.name} width={1200} height={800} priority className="rounded-[2rem] border border-cyan-700/20 shadow-glow"/><div><span className="section-kicker">Product</span><h1 className="text-4xl font-black text-slate-950 sm:text-6xl">{p.name}</h1><p className="mt-5 text-lg leading-8 text-slate-700">{p.description}</p>{p.imageSource && <p className="mt-3 text-sm text-slate-500">Reference product image: {p.imageSource}</p>}<div className="mt-8 grid gap-6 sm:grid-cols-2"><Spec title="Features" items={p.features}/><Spec title="Applications" items={p.applications}/><Spec title="Specifications" items={p.specifications}/></div></div></div><section className="mt-16 grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><div className="tech-card"><h2 className="text-2xl font-bold">Request datasheet or quote</h2><p className="mt-3 text-slate-600">Share your load, enclosure, connectivity, and manufacturing requirements. We can customize firmware, cloud APIs, and PCB variants.</p></div><InquiryForm interest={p.name}/></section></main>}
function Spec({title,items}:{title:string;items:string[]}){return <div className="rounded-3xl border border-cyan-700/10 bg-white/85 p-5"><h2 className="font-bold text-slate-950">{title}</h2><ul className="mt-4 space-y-2">{items.map((i)=><li key={i} className="flex gap-2 text-sm text-slate-700"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-accent"/>{i}</li>)}</ul></div>}
