import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Factory, Gauge, RadioTower } from "lucide-react";
import { site } from "@/data/site";

function PCBTrace() {
  return <svg className="absolute inset-0 h-full w-full opacity-40" viewBox="0 0 1200 700" aria-hidden><g fill="none" stroke="#22d3ee" strokeWidth="2" strokeDasharray="12 14"><path className="animate-trace" d="M90 560H300V420H520V250H780V330H1060"/><path className="animate-trace" d="M140 180H360V310H620V150H990"/><path className="animate-trace" d="M210 640V500H450V600H900V470H1120"/></g></svg>;
}

export function Hero() {
  return <section className="relative overflow-hidden bg-radial"><PCBTrace /><div className="absolute inset-0 bg-grid bg-[size:64px_64px] [mask-image:linear-gradient(to_bottom,black,transparent)]" /><div className="container-pad relative grid min-h-[760px] items-center gap-12 py-20 lg:grid-cols-[1.05fr_.95fr]"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-700/20 bg-cyan-100/80 px-4 py-2 text-sm font-medium text-cyan-800"><RadioTower size={16}/> Industrial IoT · Embedded · Robotics · AI Vision</div><h1 className="max-w-4xl text-5xl font-black tracking-tight text-slate-950 sm:text-6xl lg:text-7xl">{site.tagline}</h1><p className="mt-6 max-w-2xl text-xl leading-8 text-slate-700">From concept to manufacturing, we design intelligent embedded systems, industrial IoT solutions, robotics platforms, and automation products.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Link href="/products" className="inline-flex items-center justify-center gap-2 rounded-full bg-primary px-7 py-4 font-bold text-slate-950 shadow-glow transition hover:bg-accent">Explore Products <ArrowRight size={18}/></Link><Link href="/contact" className="inline-flex items-center justify-center gap-2 rounded-full border border-cyan-700/25 px-7 py-4 font-bold text-cyan-900 transition hover:bg-cyan-100/80">Start Your Project</Link></div><div className="mt-10 grid max-w-xl grid-cols-3 gap-3 text-sm text-slate-700"><span className="glass rounded-2xl p-4"><Factory className="mb-2 text-accent"/>DFM Ready</span><span className="glass rounded-2xl p-4"><Gauge className="mb-2 text-accent"/>OTA & MQTT</span><span className="glass rounded-2xl p-4"><RadioTower className="mb-2 text-accent"/>Cloud Native</span></div></div><div className="relative"><div className="absolute -inset-8 rounded-full bg-cyan-200/50 blur-3xl"/><Image src="/images/catalog/hero-industrial-product-lab.svg" alt="Industrial IoT, PCB traces, robotics and dashboard visuals" width={1200} height={800} priority className="relative animate-float rounded-[2rem] border border-cyan-700/20 shadow-glow"/><Image src="/images/catalog/dashboard-mqtt-operations.svg" alt="IoT dashboard visual" width={520} height={340} className="absolute -bottom-10 -left-6 hidden rounded-3xl border border-cyan-700/20 shadow-panel lg:block"/></div></div></section>;
}
